# Generated by Django 2.2.4 on 2020-04-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.IntegerField(null=0),
        ),
    ]
