# Generated by Django 2.2.4 on 2020-04-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_exchange', '0002_auto_20200430_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.IntegerField(null=0),
        ),
    ]
