# Generated by Django 2.2.4 on 2020-04-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_exchange', '0004_auto_20200430_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='material',
        ),
        migrations.AlterField(
            model_name='industrial_material',
            name='material_source',
            field=models.ManyToManyField(blank=True, null=True, related_name='material_connection', to='material_exchange.Company'),
        ),
    ]
